/* kernel/fallback_kernel.c
 *
 * SageOS-RV kernel entry point (C layer).
 *
 * Entry symbol:  sage_kernel_main  (called from boot/arch/rv64/boot.S)
 *
 * Architecture:
 *   1. UART 16550A init
 *   2. PMM bump allocator init (used by vmm.c)
 *   3. Wire uart_putc / uart_getchar into MetalVM I/O callback fields
 *   4. metal_vm_init(&sage_vm)
 *   5. metal_vm_load_binary(&sage_vm, blob, size)
 *   6. metal_vm_run(&sage_vm)   -- executes kmain.sgvm
 *
 * Compile flags (enforced by sagemake):
 *   -march=rv64imac_zicsr_zifencei -mabi=lp64
 *   -nostdlib -ffreestanding -O2
 *   -DSAGE_BARE_METAL -DSAGE_METAL_VM
 */

#include <stdint.h>
#include <stddef.h>
#include "metal_vm.h"
#include "metal_rv64_vm.h"

/* --------------------------------------------------------------------------
 * UART 16550A  (QEMU virt / LicheeRV Nano base address)
 * -------------------------------------------------------------------------- */
#define UART_BASE  0x10000000UL
#define UART_THR   0
#define UART_RBR   0
#define UART_IER   1
#define UART_FCR   2
#define UART_LCR   3
#define UART_LSR   5
#define UART_THRE  0x20
#define UART_DR    0x01

static inline void    _w8(uint64_t a, uint8_t v) { *(volatile uint8_t *)a = v; }
static inline uint8_t _r8(uint64_t a)            { return *(volatile uint8_t *)a; }

static void uart_init(void) {
    _w8(UART_BASE + UART_IER, 0x00);
    _w8(UART_BASE + UART_FCR, 0xC7);
    _w8(UART_BASE + UART_LCR, 0x03);
}

static void uart_putc(char c) {
    while ((_r8(UART_BASE + UART_LSR) & UART_THRE) == 0);
    _w8(UART_BASE + UART_THR, (uint8_t)c);
}

static int uart_getchar(void) {
    if (_r8(UART_BASE + UART_LSR) & UART_DR)
        return (int)_r8(UART_BASE + UART_RBR);
    return -1;
}

static void uart_puts(const char *s) {
    while (*s) uart_putc(*s++);
}

/* --------------------------------------------------------------------------
 * PMM — simple bump allocator
 *
 * vmm.c forward-declares:  extern uint64_t pmm_alloc(void);
 * We carve 4 KiB pages out of a static arena placed above the kernel.
 * 256 pages = 1 MiB, plenty for early Sv39 page table bootstrap.
 * -------------------------------------------------------------------------- */
#define PMM_PAGE_SIZE   4096UL
#define PMM_NUM_PAGES   256

static uint8_t  _pmm_arena[PMM_PAGE_SIZE * PMM_NUM_PAGES]
    __attribute__((aligned(PMM_PAGE_SIZE)));
static uint32_t _pmm_next = 0;

uint64_t pmm_alloc(void) {
    if (_pmm_next >= PMM_NUM_PAGES)
        return 0;   /* OOM */
    uint64_t page = (uint64_t)(uintptr_t)&_pmm_arena[_pmm_next * PMM_PAGE_SIZE];
    _pmm_next++;
    /* Zero the page */
    uint64_t *p = (uint64_t *)(uintptr_t)page;
    for (size_t i = 0; i < PMM_PAGE_SIZE / sizeof(uint64_t); i++)
        p[i] = 0;
    return page;
}

/* --------------------------------------------------------------------------
 * Linker symbols -- generated by objcopy (relative-path embed)
 *
 *   cd ${SCRIPT_DIR} && objcopy ... kernel/kmain.sgvm
 *   -> _binary_kernel_kmain_sgvm_start / _end
 *
 *   cd ${SCRIPT_DIR} && objcopy ... shell/shell.sgvm
 *   -> _binary_shell_shell_sgvm_start / _end
 * -------------------------------------------------------------------------- */
extern const uint8_t _binary_kernel_kmain_sgvm_start[];
extern const uint8_t _binary_kernel_kmain_sgvm_end[];
extern const uint8_t _binary_shell_shell_sgvm_start[];
extern const uint8_t _binary_shell_shell_sgvm_end[];

/* --------------------------------------------------------------------------
 * Static MetalVM instance  (zero dynamic allocation)
 * -------------------------------------------------------------------------- */
static MetalVM sage_vm;

/* --------------------------------------------------------------------------
 * Halt
 * -------------------------------------------------------------------------- */
static void _halt(const char *reason) __attribute__((noreturn));
static void _halt(const char *reason) {
    uart_puts("\n[FATAL] ");
    uart_puts(reason);
    uart_puts("\n[FATAL] System halted.\n");
    for (;;) __asm__ volatile("wfi");
}

/* --------------------------------------------------------------------------
 * sage_kernel_main -- called from boot/arch/rv64/boot.S
 * -------------------------------------------------------------------------- */
void sage_kernel_main(uint64_t hart_id, uint64_t dtb_addr) {
    (void)hart_id;
    (void)dtb_addr;

    uart_init();
    uart_puts("[MetalVM] Initializing...\n");

    /* Init VM state (zeroes all pools) */
    metal_vm_init(&sage_vm);

    /* Wire I/O callbacks -- direct fields on MetalVM struct */
    sage_vm.write_char = uart_putc;
    sage_vm.read_char  = uart_getchar;

    /* Validate kernel blob */
    const uint8_t *kblob = _binary_kernel_kmain_sgvm_start;
    int            ksz   = (int)(_binary_kernel_kmain_sgvm_end - kblob);

    if (ksz <= 0)
        _halt("kmain.sgvm blob is empty -- rebuild with ./sagemake build");

    uart_puts("[MetalVM] Loading kmain.sgvm...\n");

    int load_ok = metal_vm_load_binary(&sage_vm, kblob, ksz);
    if (load_ok != 0)
        _halt("metal_vm_load_binary() failed");

    uart_puts("[MetalVM] Running kernel...\n");

    int rc = metal_vm_run(&sage_vm);

    if (rc != 0) {
        uart_puts("[MetalVM] kmain.sgvm exited with error\n");
        if (sage_vm.error_msg) uart_puts(sage_vm.error_msg);
    } else {
        uart_puts("[MetalVM] kmain.sgvm returned (unexpected)\n");
    }

    _halt("Kernel returned from MetalVM");
}
