/* kernel/metal_vm.h — in-tree shim for SageLang's MetalVM header
 *
 * When building SageOS-RV with SAGELANG_CORE pointing at the SageLang
 * repository, the real header is used directly.  If it isn't found the
 * build system copies it here during the 'setup-metalvm' step in sagemake.
 *
 * In either case, consumer code in the kernel only needs:
 *   #include "metal_vm.h"
 */

#ifndef SAGEOS_METAL_VM_SHIM_H
#define SAGEOS_METAL_VM_SHIM_H

/* The build system sets -DMETAL_VM_HEADER_PATH=\"...\" when the SageLang
 * include directory is available.  Fall through to the local copy otherwise. */
#ifdef METAL_VM_HEADER_PATH
#  include METAL_VM_HEADER_PATH
#else
/* ------------------------------------------------------------------
 * Bundled copy — generated by sagemake setup-metalvm.
 * Re-run './sagemake setup-metalvm' to refresh from upstream.
 * ----------------------------------------------------------------*/
#  include "metal_vm_bundled.h"
#endif

#endif /* SAGEOS_METAL_VM_SHIM_H */
